### ISSUE TITLE
Connect from macOS

### ISSUE THREAD

**Issue by madhavajay** [bablokb/pi-btnap#3]
Is there a way I could connect to the PAN on a Raspberry Pi from a Mac?
I see in the networking options of a mac if you are connected via bluetooth and a PAN is detected you can connect to it.

I see other services are broadcast when I connect such as Audio and causes my mac to try to pipe its audio through bluetooth as though the pi was a speaker.

Is it a matter of providing some kind of additional "PAN" service for devices that connect?

**Comment by bablokb** [comment]
You should check the services running on your Pi. pi-btnap only advertises the PAN, but other services automatically started by Raspbian might advertise additional services (bluetooth can do many things at the same time). So you should either shutdown these services or tell your mac not to connect automatically. 

Best, Bernhard

**Comment by madhavajay** [comment]
Its weird coz i got it working by accident but dont know how to repeat it. I had to disconnect from WiFi before the Bluetooth connection would assign me an IP which was weird.

Unfortunately most of the guides are for Bluez 4 with some old tool called pand.

I will try another guide for bluez 5 when i get a chance.
