### ISSUE TITLE
android fails to get internet access via NAP

### ISSUE THREAD

**Issue by inbsarda** [bablokb/pi-btnap#4]
Hi,
We established nap using  btnap.service.  Android device successfully connects via bluetooth and gets ip assigned to it. But fails to access internet. But with the same nap ios device can access internet. Can you please help, whats wrong we are doing?

Thanks.

**Comment by bablokb** [comment]
Hi,
it could be that Android does not set the ip-configuration correctly. Can you see which IP-address and which DNS-server is assigned within Android? Also, have you checked your /etc/dnsmasq.conf. The installation-script will create it with a domain of example.com, maybe Android stumbles because of this. Maybe you also must set an upstream DNS-server in /etc/dnsmasq.conf (e.g. "server=8.8.8.8" to use the google DNS-server). dnsmasq should then pass on any DNS-requests. 

Bernhard

**Comment by inbsarda** [comment]
Hi Bernhard,
Thanks for the reply.

I modified /etc/dnsmasq as you suggested. But still android fails to access
internet. Following is the configuration that we set.

1. *root@beaglebone:/home/debian# cat /etc/dnsmasq.conf*
interface=br0
expand-hosts
server=8.8.8.8
domain=example.com
dhcp-range=192.168.20.100,192.168.20.150,12h


*2. root@beaglebone:/home/debian# ifconfig*
bnep0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::21a:7dff:feda:7111  prefixlen 64  scopeid 0x20<link>
        ether 00:1a:7d:da:71:11  txqueuelen 1000  (Ethernet)
        RX packets 28  bytes 2260 (2.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 15908  bytes 4452783 (4.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.70.99  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::9a84:e3ff:fe96:9ae8  prefixlen 64  scopeid 0x20<link>
        ether 00:1a:7d:da:71:11  txqueuelen 1000  (Ethernet)
        RX packets 2378  bytes 222981 (217.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 42  bytes 7556 (7.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=-28605<UP,BROADCAST,RUNNING,MULTICAST,DYNAMIC>  mtu 1500
        inet 192.168.70.72  netmask 255.255.255.0  broadcast 192.168.70.255
        inet6 fe80::9a84:e3ff:fe96:9ae8  prefixlen 64  scopeid 0x20<link>
        ether 98:84:e3:96:9a:e8  txqueuelen 1000  (Ethernet)
        RX packets 36949  bytes 10659660 (10.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 267  bytes 32521 (31.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 55

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 440  bytes 34916 (34.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 440  bytes 34916 (34.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

usb0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.7.2  netmask 255.255.255.252  broadcast 192.168.7.3
        inet6 fe80::9a84:e3ff:fe96:9aea  prefixlen 64  scopeid 0x20<link>
        ether 98:84:e3:96:9a:ea  txqueuelen 1000  (Ethernet)
        RX packets 1044  bytes 106096 (103.6 KiB)
        RX errors 0  dropped 4  overruns 0  frame 0
        TX packets 298  bytes 54801 (53.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

usb1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.6.2  netmask 255.255.255.252  broadcast 192.168.6.3
        ether 98:84:e3:96:9a:ed  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


3.  *root@beaglebone:/home/debian# brctl show*
bridge name     bridge id               STP enabled     interfaces
br0             8000.001a7dda7111       no                  bnep0

    eth0

4. *Android gets ip : 192.168.70.59 and DNS server ip : 192.168.1.243, 8.8.8.8 ,  4.4.2.2

**Comment by inbsarda** [comment]
Please find the attached image for android network configuration.

**Comment by bablokb** [comment]
Hi,
your dhcp-range in /etc/dnsmasq.conf does not fit to your ip-configuration. It uses 192.168.20.xxx and not 192.168.70.xxx. So I assume the Android-device gets its ip-address from a second dhcp in your network.
Bernhard

**Comment by inbsarda** [comment]
Yes, I think android device gets its ip from eth0 interface instead of bridge br0. How to resolve this problem? If i down eth0, android fails to get ip.

**Comment by bablokb** [comment]
As said above, you have to change the ip-range in dnsmasq.conf.
