### ISSUE TITLE
Cannot pair with Galaxy S7 Edge

### ISSUE THREAD

**Issue by bigAtta** [bablokb/pi-btnap#6]
I can't pair my phone with the Pi. The raspberry detects my phone, when I type the _pair_ command, phone seems to pair successfully. Right after I confirm the security PIN on both devices my phone disconnects.

**Comment by bablokb** [comment]
Pairing and connecting are two different things. Once paired, both devices should automatically connect once an application asks for a connection.

I'm closing this issue since it is not related to this project.
